import { createAsyncThunk, createSlice, current } from "@reduxjs/toolkit";
// import { fetchCart } from "./cartAPI"; ??

const initialState = { cart: {}, deals: [] };

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

// export const incrementAsync = createAsyncThunk(
//   "cart/fetchCart",
//   async (amount) => {
//     const response = await fetchCart(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );

// TODO: error handling/JSONBin

const checkDiscountCode = (cart, codeUserEntered) => {
  for (const cartItem in cart) {
    const item = cart[cartItem];
    const {
      price,
      deal,
      discountCode,
      deal: { percentOff },
    } = item;

    if (
      deal &&
      percentOff &&
      discountCode.toLowerCase() === codeUserEntered.toLowerCase()
    ) {
      item.dealPrice = ((price / 100) * (100 - percentOff)).toFixed(2);
    }
  }
  return cart;
};

const checkTwoForDeals = (cart, deal) => {
  for (const cartItem in cart) {
    const item = cart[cartItem];
    if (item.deal && item.deal.twoFor && item.deal.twoFor === deal) {
      item.dealPrice = deal / 2;
      console.log(item);
    }
  }
  return cart;
};

const checkCartDeals = (cart, prodDeal) => {
  // const cart = { ...state.cart };
  const dealCount = Object.values(cart).filter(({ deal }) => deal === prodDeal);
  console.log(dealCount);
  if (dealCount.length < 2) {
    // remove deal from existing product
    for (const cartItem in cart) {
      const item = cart[cartItem];

      if (item.deal === prodDeal) {
        delete item.dealPrice;
      }
    }
  }
  return cart;
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state, action) => {
      console.log("incremement");
      const {
        payload: {
          id,
          name,
          brand,
          shortName,
          price,
          quantity,
          deal,
          discountCode,
        }, // TODO: name is reserved??
      } = action;
      // console.log(action);
      console.log(id, name, brand, shortName, price, quantity, deal);

      const { cart, deals } = state;
      let qty = cart[id] ? cart[id].qty + quantity : quantity;

      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes

      state.cart = {
        ...state.cart,
        [id]: { name, brand, shortName, price, qty, deal, discountCode },
      };

      // keep track of products in '2 for' deals
      if (deal.twoFor) {
        const currentDeal = deal.twoFor;
        if (deals.indexOf(currentDeal) === -1) {
          deals.push(currentDeal);
        } else {
          state.cart = checkTwoForDeals({ ...state.cart }, currentDeal);
        }
      }
      console.log(state.cart);
    },
    decrement: (state, action) => {
      const {
        payload: { id, all },
      } = action;

      const prod = state.cart[id];
      let prodQty = prod.qty;
      if (all || prodQty === 1) {
        delete state.cart[id];
      } else {
        state.cart = { ...state.cart, [id]: { ...prod, qty: --prodQty } };
      }
      //  check if the product was in a '2 for' deal
      if (prod.deal) {
        // check products in cart that have the same deal as the removed product
        state.cart = checkCartDeals(state.cart, prod.deal);
      }
    },
    applyDiscountCode: (state, action) => {
      console.log(action);
      state.cart = checkDiscountCode(state.cart, action.payload);
    },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action) => {
    //   state.value += action.payload;
    // },
  },
  //   // The `extraReducers` field lets the slice handle actions defined elsewhere,
  //   // including actions generated by createAsyncThunk or in other slices.
  //   extraReducers: (builder) => {
  //     builder
  //       .addCase(incrementAsync.pending, (state) => {
  //         state.status = "loading";
  //       })
  //       .addCase(incrementAsync.fulfilled, (state, action) => {
  //         state.status = "idle";
  //         state.value += action.payload;
  //       });
  //   },
});

export const {
  increment,
  decrement,
  incrementByAmount,
  selectCount,
  applyDiscountCode,
  toggleCart,
} = cartSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.cart.value)`
export const selectCart = (state) => state.cart.cart;

export const applyDiscounts = (discountCode) => {
  const cart = selectCart();
  checkDiscountCode(cart, discountCode);
};

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = (amount) => (dispatch, getState) => {
  const currentValue = selectCart(getState());
  if (currentValue % 2 === 1) {
    dispatch(incrementByAmount(amount));
  }
};

export default cartSlice.reducer;
